name: strapi-server

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build image
        run: >-
          docker buildx build 
            -t $IMAGE:$GITHUB_SHA 
            --platform $BUILDX_PLATFORMS
            --push
            packages/strapi-server
        env:
          IMAGE: stevenlsjr/blog-strapi-server
          BUILDX_PLATFORMS: linux/arm64,linux/amd64